[package]
name = "balance-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
solana-client = "1.17.6"
solana-program = "1.17.6"
solana-sdk = "1.17.6"
